services:
  sprintos:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - '4100:4100'
    volumes:
      - ../data:/app/data
    environment:
      - NODE_ENV=production
      - PORT=4100
      - DATA_DIR=/app/data
